<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>assets\icon.ico</ApplicationIcon>
    <AssemblyName>Payroll Management</AssemblyName>
    <RootNamespace>PayrollManagement</RootNamespace>
    <AssemblyTitle>Payroll Management</AssemblyTitle>
    <Product>Payroll Management</Product>
    <Title>Payroll Management</Title>
    <Description>Payroll Management</Description>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="assets\icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.0-rc2" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
  </ItemGroup>

</Project>
